import { createElement } from 'lwc';
import Fall23UIRecordAPIComponent from 'c/fall23UIRecordAPIComponent';

describe('c-fall23-ui-record-api-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fall23-ui-record-api-component', {
            is: Fall23UIRecordAPIComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});